liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'
    filter_sets:
        cache: ~
        profile_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: inset }
        profile_large:
            quality: 80
            filters:
                thumbnail: { size: [800, 800], mode: inset }
                strip: ~  # Supprime les métadonnées EXIF
        profile_original:
            quality: 85
            filters:
                thumbnail: { size: [1200, 1200], mode: inset }
                strip: ~
                auto_rotate: ~  # Rotation automatique selon EXIF
