vich_uploader:
    db_driver: orm
    mappings:
        song_pdf:
            uri_prefix: /uploads/song_pdf
            upload_destination: '%kernel.project_dir%/public/uploads/song_pdf'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profile_pictures:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer